import Head from 'next/head'
import styles from '@src/styles/Home.module.scss'
import Header from '@components/Header/Header'
import dayjs from 'dayjs';

import RootLayout from './layout'
import Cargo from '@components/Cargo/Cargo'
import cn from 'classnames'
import { useState } from 'react';
import Vehicle from '@components/Vehicle/Vehicle';
import { useRouter } from 'next/router';

// export async function getServerSideProps() {
//   const res = await fetch(`https://cargo-transportation.onrender.com/cargo/getList?city=&startDate=&endDate=&page=1&limit=10`)
//   const data = await res.json()
//   return { props: { data } }
// }
export default function Home({ data }: any) {
  const [show, setShow] = useState(true)
  const router = useRouter();
  return (
    <>
      <Head>
        <title>Грузовик+</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main >
        {/* <Header/> */}
        <div className="main">
          <div className={styles.navBlock}>
            <div>
              <div className={cn( styles.navItems,{
                  [styles.active]: show
                })} onClick={()=>setShow(true)}>Грузы</div>
                <div className={cn( styles.navItems,{
                  [styles.active]: !show
                })} onClick={()=>setShow(false)}>Транспорт</div>
            </div>
              

              <div>
                <button className='btnBlack' onClick={()=> router.push('/addCargo')}>Добавить груз</button>
                <button className='btnBlack' onClick={()=> router.push('/addCar')}>Добавить транспорт</button>
              </div>
           
              {/* <Cargo /> */}
          </div>
             {
              show ? <Cargo/> : <Vehicle/>
            }
          
        
          {/* {data.cargos.map((item: any)=> ( <div>{item.id}</div>))} */}
          {/* <RootLayout >
                <div>
                  prikol
                </div>
            </RootLayout> */}

        </div>
      </main>
    </>
  )
}
