import Head from 'next/head'
import styles from '@src/styles/Home.module.css'
import Header from '@components/Header/Header'

import RootLayout from './layout'
import Cargo from '@components/Cargo/Cargo'
import TextField from '@mui/material/TextField'

export async function getServerSideProps() {
  // Fetch data from external API
  const res = await fetch(`https://cargo-transportation.onrender.com/cargo/getList?city=&startDate=&endDate=&page=1&limit=10`)
  const data = await res.json()

  // Pass data to the page via props
  return { props: { data } }
}
export default function Home({data} :any) {
  console.log(data)
  return (
    <>
      <Head>
        <title>Грузовик+</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main >
          {/* <Header/> */}
          <div className={styles.main}>
            <div>
              Грузы
            </div>
            <div>
                Транспорт
            </div>
            <Cargo/>
            <TextField
          
                placeholder='Откуда'
                id="outlined-size-small"
            
                size="small"
            />
             <TextField
          
          placeholder='Куда'
          id="outlined-size-small"
          
          size="small"
      />
          {data.cargos.map((item: any)=> ( <div>{item.id}</div>))}
            {/* <RootLayout >
                <div>
                  prikol
                </div>
            </RootLayout> */}
              
          </div>
      </main>
    </>
  )
}
